### ISSUE TITLE
netcheck.sh -i gives wrong scriptname at systemd service

### ISSUE THREAD

**Issue by onexp** [TristanBrotherton/netcheck#10]
Hello,

I just found your script and I am testing it now. Seems very nice. Thanks for your effort.

I found one little bug in your script at line 236:

`ExecStart=$VAR_SCRIPTLOC/VAR_SCRIPTNAME`

After I installed it as a service with netcheck.sh -i my systemd service looked like this:

>[Unit]
>
>Description=Netcheck Service
>
>[Service]
>WorkingDirectory=/opt/netcheck/
>ExecStart=/opt/netcheck/VAR_SCRIPTNAME
>
>[Install]
>WantedBy=multi-user.target`

So the service failed to start.

Please change your script at line 236 to:

`ExecStart=$VAR_SCRIPTLOC/$VAR_SCRIPTNAME`

After I did it, it worked fine for me.

**Comment by TristanBrotherton** [comment]
Thanks for the bug report and the compliments! I'll check in a quick fix for that now.
