### ISSUE TITLE
[FEATURE] Option to force speedtest installation

### ISSUE THREAD

**Issue by jdorel** [TristanBrotherton/netcheck#13]
Hi,
I'm currently installing netcheck through ansible, but during the first run, it asks to install speedtest. Could there be an option to answer yes automatically ?

**Comment by TristanBrotherton** [comment]
Hi Jonas,

If I were you I would just include Speedtest in your ansible install. Probably the easiest route to take.

**Comment by jdorel** [comment]
FYI, here is the ansible role : https://gitlab.com/jdorel-ansible-collections/services/-/tree/master/roles/netcheck

**Comment by TristanBrotherton** [comment]
Thanks I will add a link to that in the README
