### ISSUE TITLE
Not continually checking

### ISSUE THREAD

**Issue by JC1738** [TristanBrotherton/netcheck#14]
@TristanBrotherton Ran across your repo, great project.  I have started using and can't seem to get the check to work after the first call.  

I have done ./netcheck -w -c 30 running on Linux mint 20.1 and it does the first check, but never does a second check.  The program is still up and the web interface is working on port 9000 but no additional checks are logged on the command line nor the connection.log file.  

Any ideas of what to try?

Thank you!
Jim

**Comment by TristanBrotherton** [comment]
Hi Jim,

I haven't seen this issue before. Could you let me know if the issue occurs using the default interval? (Omitting the - c option).

**Comment by TristanBrotherton** [comment]
Also it may not be obvious and I intend to change this behavior but the web interface does not refresh data unless you click on the "last checked n seconds ago"

**Comment by JC1738** [comment]
@TristanBrotherton correct, I tried without the -c at first and that didn't work, that's why I tried to force the issue with -c.  Yes, saw that with the web, same thing happens with or without -w.

**Comment by TristanBrotherton** [comment]
Are you running it as a service or manually?

If it's manually I'll take a look and see where we can add some extra logging to find out what it's doing.

**Comment by JC1738** [comment]
Running manually, thanks yes, any additional logging might help track what's going on.

**Comment by JC1738** [comment]
@TristanBrotherton  I figured out it was my understanding after all.  I added some echo's and things are working as you wrote.  My expectation was the speed test would reoccur every -c seconds.  That's not the case, just the check itself if network was up.  I guess a feature request or a consideration would be an option to run the speed check every Y seconds (maybe another config flag)?  I might play around and submit a PR if I get something that I like working.  Thanks again and sorry for the confusion.

**Comment by TristanBrotherton** [comment]
Aha got it. Yes the speed check consumes a decent amount of bandwidth so running it at each check could introduce other issues with bandwidth or overlapping checks. That's why we run it only after a change in the network is detected. Thanks for letting me know I'll close this.
