### ISSUE TITLE
ifconfig is required, but never checked with script, replace with 'ip' ?

### ISSUE THREAD

**Issue by jayshomebrew** [TristanBrotherton/netcheck#19]
$ ./netcheck.sh -w
-----------------------------------------------------------------------------
Web Interface:     Enabled 
                   http://localhost:9000
./netcheck.sh: line 124: ifconfig: command not found

`uname -a`
`Linux DietPi 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`

reference:
https://ubuntu.com/blog/if-youre-still-using-ifconfig-youre-living-in-the-past

**Comment by TristanBrotherton** [comment]
Some popular platforms (like OSX) don't ship with `ip` - so we would need to implement some logic to check for either `ifconfig` or `ip` and use whichever they found.
