### ISSUE TITLE
No issue, just wanted to say THANK YOU!

### ISSUE THREAD

**Issue by briantully** [TristanBrotherton/netcheck#2]
Hi there - 

In an attempt at documenting my internet provider's (Optimum) frequent outages, I was planning on writing my own script. So imagine my delight upon finding this wonderful `netcheck` shell script, which is exactly what I was envisioning. Thank you so much for developing and sharing this very helpful tool!

**Comment by TristanBrotherton** [comment]
You're welcome - Thats the exact issue I was trying to resolve too. Glad I could be helpful to you! - Be well. T
