### ISSUE TITLE
Does the service handle the webinterface?

### ISSUE THREAD

**Issue by daveodwyer** [TristanBrotherton/netcheck#20]
Having already ran

`netcheck.sh -i`

How do you initiate the webinterface? Or does the webservice not also handle the webinterface?

If I run `netcheck.sh -w` afterwards, it starts the application in a separate process - not through the service

**Comment by TristanBrotherton** [comment]
`-i` will help you setup netcheck as a service. its just a convenience helper function. `-w` runs a local webserver and would be a separate service. You could setup the service manually to run the webinterface, or simply serve the HTML manually to receive the same result. Its a simple HTML page that loads the log.
