### ISSUE TITLE
icmp ping/etc?

### ISSUE THREAD

**Issue by goffy59** [TristanBrotherton/netcheck#22]
Hello,

I am using netcheck on a couple things. One of them runs on a raspberry pi at my house (working great). The other I have on a VPS using a dynamic dns of my home internet to check remotely from another state. The VPS isn't working correctly from what I can see. I have made a firewall rule to allow icmp/ping requests (pfsense). But my netcheck (vps) says that connection is down and its not down. I realize this could easily be level3 or some other middle isp  (using netcheck from Arizona - Georgia). I realize there are other solutions that can do exactly what I am attempting but I am used to netcheck and I like it. Am I missing anyhthing. Is netcheck using icmp to ping to check connection uptime or something different. If its not icmp I could probably add another rule to accomodate whatever type of request netcheck is using to see if a connection is up or down. I am just not sure. I am not a programmer. Thanks in advance! I appreciate your program. Thanks.

edit, i am using this as a service and modifying the default host (google).

**Comment by TristanBrotherton** [comment]
Hi there, if you look at line 206, you can see the code that is run to check the uptime:
`    nohup wget -q --tries=5 --timeout=20 -O - $VAR_HOST > /dev/null 2>&1`

It is essentially just running wget, which is the same as your browser requesting the host that you’ve setup. So if you’re checking your own host, you’ll need to have an HTTP server running on port 80.

**Comment by goffy59** [comment]
Thank you!
