### ISSUE TITLE
Script not working under Zshell - unable to find python directory?

### ISSUE THREAD

**Issue by ricardorodrigues-ca** [TristanBrotherton/netcheck#23]
Output: 

-----------------------------------------------------------------------------
SpeedTest-CLI:     Installed
Logging to:        log/connection.log
************ Monitoring started at: Wed 20 Jul 2022 00:48:06 EDT ************
CONNECTED LINK SPEED:
env: python: No such file or directory
-----------------------------------------------------------------------------

<img width="629" alt="netcheck-error" src="https://user-images.githubusercontent.com/34870024/179899432-3309dd13-da22-46f3-abb3-bc6f6b97df92.png">

**Comment by TristanBrotherton** [comment]
Can you verify you have a working python installation? If you're unable to do that / do not wish too than you can run netcheck without using the speedtest which requires python
