### ISSUE TITLE
incorrect downtime detected

### ISSUE THREAD

**Issue by goffy59** [TristanBrotherton/netcheck#25]
Hello,

I noticed every 5 second at certain intervals it will show 5 seconds of downtime. I increased the checking in the script to 10 seconds and it does the same thing. Any ideas?

************ Monitoring started at: Mon 25 Jul 2022 23:14:54 BST ************
LINK DOWN:                                       Mon 25 Jul 2022 23:14:55 BST
LINK RECONNECTED:                                Mon 25 Jul 2022 23:15:00 BST
TOTAL DOWNTIME:                                  0 minutes and 5 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
************ Monitoring started at: Mon 25 Jul 2022 23:15:38 BST ************
LINK DOWN:                                       Mon 25 Jul 2022 23:15:38 BST
LINK RECONNECTED:                                Mon 25 Jul 2022 23:15:44 BST
TOTAL DOWNTIME:                                  0 minutes and 6 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
************ Monitoring started at: Mon 25 Jul 2022 15:50:50 MST ************
LINK DOWN:                                       Mon 25 Jul 2022 15:50:51 MST
LINK RECONNECTED:                                Mon 25 Jul 2022 15:50:56 MST
TOTAL DOWNTIME:                                  0 minutes and 5 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
LINK DOWN:                                       Wed 27 Jul 2022 14:53:26 MST
LINK RECONNECTED:                                Wed 27 Jul 2022 14:53:32 MST
TOTAL DOWNTIME:                                  0 minutes and 6 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
************ Monitoring started at: Wed 27 Jul 2022 19:53:44 MST ************
LINK DOWN:                                       Wed 27 Jul 2022 22:42:51 MST
LINK RECONNECTED:                                Wed 27 Jul 2022 22:43:01 MST
TOTAL DOWNTIME:                                  0 minutes and 10 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
LINK DOWN:                                       Wed 27 Jul 2022 23:02:49 MST
LINK RECONNECTED:                                Wed 27 Jul 2022 23:02:59 MST
TOTAL DOWNTIME:                                  0 minutes and 10 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------

I have this running on a Single Board Computer via ethernet cable to my network. I am not noticing any drops. Also, when the internet does actually fail netcheck works pretty good and is accurate. But these "drops" are not actually drops from what I experience. Any help would be appreciated. Thanks!

-goffy59

**Comment by TristanBrotherton** [comment]
I have not seen that behavior before, you may want to check nothing is blocking the GET request to the host you are using (default is google). If it is a low powered device perhaps it is just taking too long to make the requests?

**Comment by TristanBrotherton** [comment]
Additionally you could try running on a desktop / laptop on the same network to see if the issue is related to your hardware.

**Comment by mfide** [comment]
@TristanBrotherton I have the same problem on my Ubuntu 22 server. I set to check the connectivity every minute and see below log what I get.
If I set to check it every 10 sec, then I get 10 sec down times. These 1 minute down time reports are not correct. 
When I have a real down time for example about 60 minutes, it is reported correctly.

```
LINK DOWN:                                       Tue 25 Jul 2023 01:58:01 +03
LINK RECONNECTED:                                Tue 25 Jul 2023 01:59:02 +03
TOTAL DOWNTIME:                                  1 minutes and 1 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 8.789 ms
                                                 Download: 486.60 Mbit/s
                                                 Upload: 240.47 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Tue 25 Jul 2023 06:57:48 +03
LINK RECONNECTED:                                Tue 25 Jul 2023 06:58:48 +03
TOTAL DOWNTIME:                                  1 minutes and 0 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 31.103 ms
                                                 Download: 248.27 Mbit/s
                                                 Upload: 12.80 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Tue 25 Jul 2023 09:49:35 +03
LINK RECONNECTED:                                Tue 25 Jul 2023 09:50:36 +03
TOTAL DOWNTIME:                                  1 minutes and 1 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 23.968 ms
                                                 Download: 132.15 Mbit/s
                                                 Upload: 95.34 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Tue 25 Jul 2023 23:57:43 +03
LINK RECONNECTED:                                Tue 25 Jul 2023 23:58:43 +03
TOTAL DOWNTIME:                                  1 minutes and 0 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 20.153 ms
                                                 Download: 70.94 Mbit/s
                                                 Upload: 94.51 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Wed 26 Jul 2023 03:15:36 +03
LINK RECONNECTED:                                Wed 26 Jul 2023 03:16:36 +03
TOTAL DOWNTIME:                                  1 minutes and 0 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 9.244 ms
                                                 Download: 573.18 Mbit/s
                                                 Upload: 564.68 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Wed 26 Jul 2023 06:49:56 +03
LINK RECONNECTED:                                Wed 26 Jul 2023 06:50:56 +03
TOTAL DOWNTIME:                                  1 minutes and 0 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 11.024 ms
                                                 Download: 408.86 Mbit/s
                                                 Upload: 382.65 Mbit/s
-----------------------------------------------------------------------------
LINK DOWN:                                       Wed 26 Jul 2023 07:34:41 +03
LINK RECONNECTED:                                Wed 26 Jul 2023 07:35:41 +03
TOTAL DOWNTIME:                                  1 minutes and 0 seconds.
RECONNECTED LINK SPEED:                         
-----------------------------------------------------------------------------
                                                 Ping: 11.223 ms
                                                 Download: 545.54 Mbit/s
                                                 Upload: 483.97 Mbit/s
-----------------------------------------------------------------------------

```
