### ISSUE TITLE
stop run as service

### ISSUE THREAD

**Issue by snydez** [TristanBrotherton/netcheck#26]
Hi, 
I run the netcheck with -i parameter,
and now i want to stop it.
could you please advise on how to do it?
thanks

**Comment by TristanBrotherton** [comment]
When you install it, Netcheck notifies you how to manage the service. 
To start: `sudo systemctl start netcheck`
To stop: `sudo systemctl stop netcheck`

I recommend reading up on systemctl and how to use it.
