### ISSUE TITLE
internet_status_chart.sh assumes location of logfile

### ISSUE THREAD

**Issue by superian** [TristanBrotherton/netcheck#30]
Installs this (thank you!)
Sorts issue with "#!/usr/bin/env python" in downloaded speedtest.py not working on recent Ubuntu (replaced with #!/usr/bin/python3)
Starts main script
Disconnects from network, just to see if it notices - yes!
Reconnects, also noticed - yes!
Tries internet_status_chart.sh ..

`$ ./internet_status_chart.sh 
grep: /usr/local/src/netcheck/log/connection.log: No such file or directory
      Jan     Feb     Mar       Apr     May       Jun     Jul     Aug       Sep     Oct     Nov       Dec     
    ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
Mon ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
    ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
Wed ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ./internet_status_chart.sh: line 83: 00 / commits_max: division by 0 (error token is "commits_max")
`
.. the logfile isn't at /usr/local/src/netcheck/log/connection.log, so commits_max stays at zero.

**Comment by TristanBrotherton** [comment]
[Fixed](https://github.com/TristanBrotherton/netcheck/commit/1f6a145339ed665909a30d87cd7063686a6fd8e8)
