### ISSUE TITLE
speedtest frequency between 'only on start and reconnections' and 'every connection check', please

### ISSUE THREAD

**Issue by superian** [TristanBrotherton/netcheck#31]
At the moment, I think users have three options:

Never speedcheck / only on script start
Only speedcheck on script start and on every reconnection
Speedcheck on every connection check

It would be good to be able to say 'every n connection checks' or 'every x days/hours/minutes/seconds' - I would quite like to see if the speed does vary, but I don't want to check every (by default) five seconds.

**Comment by TristanBrotherton** [comment]
If you choose to implement this feel free to submit a PR.
