### ISSUE TITLE
Relative and absolute path mixed for speedtest-cli.py

### ISSUE THREAD

**Issue by pietropelizzari** [TristanBrotherton/netcheck#4]
When the speedtest-cli.py script is called using the $VAR_SCRIPTLOC variable it is treated as a relative path, i.e. './' is added in front of it. 
https://github.com/TristanBrotherton/netcheck/blob/1862cad50e08395d9b4499251991c60897098f36/netcheck.sh#L119
I was honestly a bit lazy and I did not investigate the reason for this error but if I simply remove './' the script works fine. 

Thanks a lot for sharing it btw!

**Comment by TristanBrotherton** [comment]
I appreciate the report! Thanks for digging in. Oddly on my system it managed to run anyway. I've fixed this in the latest commit.
