### ISSUE TITLE
[FR] Version for Windows

### ISSUE THREAD

**Issue by reregaga** [TristanBrotherton/netcheck#41]
Hello,
Thank you for this script, it is useful!
I have been using it for a long time and use your script on Linux, but I also have a Windows computer and would like to install this script on it too. Are there any plans for version for Windows?

**Comment by TristanBrotherton** [comment]
I'm afraid not but I'm sure it could be fairly easily ported. I don't personally have a windows machine. If anyone wants to do that I'd happily take the PR.
