### ISSUE TITLE
install netcheck as service with alternate webinterface port

### ISSUE THREAD

**Issue by rebelgtp** [TristanBrotherton/netcheck#44]
It seems as though when trying to install as a system service and also specifying an alternate webinterface port, the port selection does not stick and the webinterface then crashes out when you have a service already listening on port 80.

The command I was using was as follows: sudo ./netcheck.sh -w -p 8080 -i

I have this installed on an nginx reverse proxy which is also already listening on port 80.

Is there a way to massage the service installation command to make the port change stick or should I go in and try to change the command that the service executes?

**Comment by TristanBrotherton** [comment]
The quickest way to resolve this would be to edit your `/etc/systemd/system/netcheck.service ` file. I don't think I wrote any logic to support a custom port in the service installation, it was only intended to be a helper.
