### ISSUE TITLE
Does not work out-of-the-box on OpenWrt

### ISSUE THREAD

**Issue by jonas-klesen** [TristanBrotherton/netcheck#48]
Hi!

This script does not work out-of-the-box on OpenWrt. That is because OpenWrt uses not really wget, but uclient-fetch, which does not have the --tries option. Removing it made it work.

Maybe this should be noted somewhere or added to the readme, because running this script on a router to me seems to be a prime use case.

Best,
Jonas

**Comment by TristanBrotherton** [comment]
Hi Jonas,

I don’t have OpenWrt to test but if you’re able to submit a pull request for the documentation I’d happily accept it
