### ISSUE TITLE
Idea - add option for run script for certain time

### ISSUE THREAD

**Issue by panartur83** [TristanBrotherton/netcheck#50]
Hello,

I'm using Your script and it is working great. 

Would this be possible to add feature to run script for certain time - eg. 24 hours?

In log there could be an info - test started at
and at the end - test ended after 24 hours - and then sum:

- how many disconnections
- working time
- disconnection time
- average speed

Best Regards 
Artur

**Comment by TristanBrotherton** [comment]
Hi Artur, thanks for the kind words. That would be outside of the scope of this script, it supports running custom scripts, i'd suggest doing this with a wrapper.
