### ISSUE TITLE
netcheck is not working properly

### ISSUE THREAD

**Issue by github4030** [TristanBrotherton/netcheck#53]
Hello
I'm using the netcheck shell script on Ubuntu 22.04 but not installing the speedtest-cli program. This shell script worked fine for a while but now when the internet is connected it shows that the internet is down. Please help me to solve this problem. Thank you

**Comment by TristanBrotherton** [comment]
I'm sorry but I can't provide individual support. I suggest you step through the script line by line to see what's not working on your system. It's very simple and only a few lines.

**Comment by vsego** [comment]
> This shell script worked fine for a while but now when the internet is connected it shows that the internet is down.

Responding here as it looks like a problem that may render this script useless for many people: for me, Google is complaining about too many connections. Use another host (`https://duckduckgo.com/` seems to work fine).
