### ISSUE TITLE
Question: monitor connection within machines of a network?

### ISSUE THREAD

**Issue by TarekHC** [TristanBrotherton/netcheck#55]
Hi @TristanBrotherton ! Thank you for the nice tool!

I have a question regarding the scope of this library. When trying to identify problems within a network it is useful to monitor not only connection to websites (e.g. google.com) but also to other machines (e.g. those you connect through ssh, and can test access through pings).

Is it possible to use this library to monitor the stability of a connection between machines of a network?

**Comment by TristanBrotherton** [comment]
Hi Tarek,

Yes. Its in the docs: `netcheck.sh -u            URL/Host to check, default is http://www.google.com`

**Comment by TarekHC** [comment]
Dear @TristanBrotherton 

Sorry to insist, but the script does not work properly when setting the URL/Host as an IP address within the network. I'm testing it right now, and even if I can perfectly connect through SSH, netcheck states the link is down.

Is this supposed to work and I'm making a mistake somewhere? Or adding an IP address as host is simply not supported?

**Comment by TristanBrotherton** [comment]
Hi Tarek,

No need to apologize! If you look at the script you'll get a better idea of how it works, it uses WGET to check for connectivity which is more of a robust indicator of functionality vs ping. So it will work just fine on your network, as long as the host is running a webserver. 

You could very easily modify the script to use PING for an internal network if you'd like.

**Comment by TarekHC** [comment]
Ok ok, now it is more clear. It is not implemented already, but it could be with a small effort.

Thanks!
