### ISSUE TITLE
Speed Test Error

### ISSUE THREAD

**Issue by zimmerzc** [TristanBrotherton/netcheck#6]
When I run the script it shows that the SpeedTest-CLI is installed, but under the "Connection Link Speed" it gives me this error:  **/usr/bin/env:  'python' : No such file or directory**.  What should I do to fix this?

**Comment by TristanBrotherton** [comment]
Looks like you don't have python installed. You'll need to have a working python environment for your OS. I can help you if you post more details on your OS.

**Comment by zimmerzc** [comment]
It’s Ubuntu 20.04, I do believe.  It’s also running LAMP.

**Comment by TristanBrotherton** [comment]
Great - follow these steps to install python and you should be good to go:

https://linuxconfig.org/install-python-2-on-ubuntu-20-04-focal-fossa-linux

**Comment by TristanBrotherton** [comment]
I'll add a check for a working python env to the script.
