### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by fastfourier666** [TristanBrotherton/netcheck#7]
Thank you for this script!

I was trying to get the webserver to work on a system which only had python 3. I found I had to change line 100 of netcheck.sh to

`  (cd $VAR_SCRIPTLOC/log; python -m http.server $1 &) &> /dev/null`

Maybe there's a way of checking for python 2 or 3 and launching the right server? I'm not too familiar with it, sorry!

**Comment by TristanBrotherton** [comment]
Thanks for the info - I'll take a look at that and see what I can do. Appreciate the thanks!

**Comment by fastfourier666** [comment]
I decided to get off my butt and have a go myself:
```
START_WEBSERVER() {
  # find python version and start webserver
  VAR_PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0])')
  case $VAR_PYTHON_VERSION in
    2)
        (cd $VAR_SCRIPTLOC/log; python -m SimpleHTTPServer $1 &) &> /dev/null  
    ;;
    3)
      (cd $VAR_SCRIPTLOC/log; python -m http.server $1 &) &> /dev/null
    ;;
  esac
}
```

**Comment by TristanBrotherton** [comment]
Looks good to me - would you like to submit a PR, or if not I can add that myself.
I really appreciate your help!

**Comment by fastfourier666** [comment]
OK. I'm new to all this but I'll give the PR a try. Thanks!

**Comment by TristanBrotherton** [comment]
Implemented a fix in latest commit.

**Comment by balakumarane** [comment]
i'm getting this error and webserver not running. my machine has python3

./netcheck.sh: line 112: VAR_PYTHON_VERSION: command not found

**Comment by TristanBrotherton** [comment]
I added a potential syntax fix, but I don’t have python 3 on my system, and can’t reproduce that error in python 2. Any chance you could try and find a fix and submit a PR?

**Comment by balakumarane** [comment]
looks like "extra space" was the issue. now webserver is working fine in my machine( Python 3).
