### ISSUE TITLE
[feature request] retry #times

### ISSUE THREAD

**Issue by MM-Lehmann** [TristanBrotherton/netcheck#9]
It would be nice to be able to specify a number of times or an interval in which connection should be retried before marking it "failed". I sometimes get intermittent disconnections of 5 seconds, i.e. only one attempt to connect fails. In practice, this is not an issue for my connection because it doesn't cause any disruptions. I am not even sure if it is an actual failure or just a slow package. I would like to specify that only connection issues longer than 30sec. are recorded.

I am not 100% sure if there is anything in the code to achieve this, but at least it's not directly exposed as a config variable.

**Comment by TristanBrotherton** [comment]
This wouldn't be a particularly hard feature to add. You could get a lot of the way there by just increasing the time between checks which is currently an option. 
 If i get around to this I'll let you know, but I'd also happily accept a PR if you decide to tackle it.
